using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Sellora.Shared.Domain;

namespace Sellora.Server.Configurations.Entities
{
    public class ItemSeedConfiguration : IEntityTypeConfiguration<Item>
    {
        // This seeds the Staff Entity with 2 of the lead developers within the organisation
        public void Configure(EntityTypeBuilder<Item> builder)
        {
            builder.HasData(
                new Item
                {
                    Id = 1,
                    ItemName = "Tofu65 Keyboard",
                    ItemPrice = 200,
                    Condition = "Well Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Very good Keyboard, Served me for many years. Hope to find a new good owner for it.",
                    ItemLocation = "Tampines West Street 42",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 23,
                    ItemClicks = 1334,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 1
                },
                new Item
                {
                    Id = 2,
                    ItemName = "Vintage Leather Jacket",
                    ItemPrice = 80,
                    Condition = "Excellent",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Stylish vintage leather jacket in excellent condition. A timeless fashion piece for any wardrobe.",
                    ItemLocation = "Orchard Road, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 45,
                    ItemClicks = 987,
                    ItemStatus = 1,
                    CategoryId = 5,
                    AppUserId = 2
                },
                new Item
                {
                    Id = 3,
                    ItemName = "Mountain Bike - Giant Talon",
                    ItemPrice = 500,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Giant Talon mountain bike in excellent condition. Perfect for off-road adventures and trail riding.",
                    ItemLocation = "Bukit Timah Nature Reserve",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 78,
                    ItemClicks = 1222,
                    ItemStatus = 1,
                    CategoryId = 13,
                    AppUserId = 3
                },
                new Item
                {
                    Id = 4,
                    ItemName = "Smart Home Security System",
                    ItemPrice = 150,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Complete smart home security system with cameras and sensors. Enhance your home's safety with advanced technology.",
                    ItemLocation = "Jurong West Street 21",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 30,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 4
                },
                new Item
                {
                    Id = 5,
                    ItemName = "Antique Chess Set",
                    ItemPrice = 120,
                    Condition = "Good",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Beautiful antique chess set with intricate detailing. Perfect for chess enthusiasts and collectors.",
                    ItemLocation = "Katong, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 15,
                    ItemClicks = 543,
                    ItemStatus = 1,
                    CategoryId = 7,
                    AppUserId = 5
                },
                new Item
                {
                    Id = 6,
                    ItemName = "KitchenAid Stand Mixer",
                    ItemPrice = 250,
                    Condition = "Slightly Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Powerful KitchenAid stand mixer, perfect for baking and cooking. In great condition, ready to mix up some delicious recipes.",
                    ItemLocation = "Serangoon Avenue 4",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 40,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 10,
                    AppUserId = 6
                },
                new Item
                {
                    Id = 7,
                    ItemName = "Baby Stroller - Chicco Bravo",
                    ItemPrice = 180,
                    Condition = "Excellent",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Chicco Bravo baby stroller in excellent condition. Stylish and comfortable for your little one.",
                    ItemLocation = "Ang Mo Kio, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 25,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 11,
                    AppUserId = 7
                },
                new Item
                {
                    Id = 8,
                    ItemName = "Healthy Meal Prep Service",
                    ItemPrice = 50,
                    Condition = "New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Subscription to a healthy meal prep service. Enjoy nutritious and delicious meals delivered to your doorstep.",
                    ItemLocation = "Novena, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 60,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 12,
                    AppUserId = 8
                },
                new Item
                {
                    Id = 9,
                    ItemName = "Yoga Mat and Accessories Set",
                    ItemPrice = 40,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Complete yoga mat and accessories set. Everything you need for a fulfilling yoga practice.",
                    ItemLocation = "Clementi, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 35,
                    ItemClicks = 987,
                    ItemStatus = 1,
                    CategoryId = 13,
                    AppUserId = 9
                },
                new Item
                {
                    Id = 10,
                    ItemName = "Cat Tree Condo",
                    ItemPrice = 60,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Multi-level cat tree condo for your feline friend. Provides entertainment and a cozy space for your cat to relax.",
                    ItemLocation = "Woodlands, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 18,
                    ItemClicks = 543,
                    ItemStatus = 1,
                    CategoryId = 14,
                    AppUserId = 10
                },
                new Item
                {
                    Id = 11,
                    ItemName = "Part-time Graphic Design Services",
                    ItemPrice = 30,
                    Condition = "Available",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Offering part-time graphic design services. Experienced designer ready to bring your ideas to life.",
                    ItemLocation = "Chinatown, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 22,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 2,
                    AppUserId = 11
                },
                new Item
                {
                    Id = 12,
                    ItemName = "Electric Scooter - Xiaomi M365",
                    ItemPrice = 300,
                    Condition = "Good",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Xiaomi M365 electric scooter in good condition. Perfect for commuting and exploring the city with ease.",
                    ItemLocation = "Raffles Place, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 33,
                    ItemClicks = 1102,
                    ItemStatus = 1,
                    CategoryId = 1,
                    AppUserId = 12
                },
                new Item
                {
                    Id = 13,
                    ItemName = "Home Theater System",
                    ItemPrice = 450,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Complete home theater system with surround sound speakers and HD projector. Elevate your movie nights at home.",
                    ItemLocation = "Hougang, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 42,
                    ItemClicks = 987,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 13
                },
                new Item
                {
                    Id = 14,
                    ItemName = "Leather Sofa - L-Shaped",
                    ItemPrice = 600,
                    Condition = "Excellent",
                    ItemDate = DateTime.Now,
                    ItemDescription = "L-shaped leather sofa in excellent condition. Stylish and comfortable for your living room.",
                    ItemLocation = "Bedok, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 38,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 14
                },
                new Item
                {
                    Id = 15,
                    ItemName = "Gaming Console - PlayStation 5",
                    ItemPrice = 700,
                    Condition = "Brand New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Brand new PlayStation 5 gaming console. Unopened and ready for an immersive gaming experience.",
                    ItemLocation = "Yishun, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 50,
                    ItemClicks = 1234,
                    ItemStatus = 1,
                    CategoryId = 8,
                    AppUserId = 15
                },
                new Item
                {
                    Id = 16,
                    ItemName = "Vintage Polaroid Camera",
                    ItemPrice = 80,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Vintage Polaroid camera in good working condition. Capture memories with the classic charm of instant photography.",
                    ItemLocation = "Choa Chu Kang, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 25,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 6,
                    AppUserId = 16
                },
                new Item
                {
                    Id = 17,
                    ItemName = "Smartwatch - Apple Watch Series 6",
                    ItemPrice = 350,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Apple Watch Series 6 in like-new condition. Stay connected and track your fitness with this advanced smartwatch.",
                    ItemLocation = "Pasir Ris, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 28,
                    ItemClicks = 789,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 17
                },
                new Item
                {
                    Id = 18,
                    ItemName = "Classic Board Games Bundle",
                    ItemPrice = 40,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Bundle of classic board games for hours of family fun. Includes Monopoly, Scrabble, and Chess.",
                    ItemLocation = "Tanjong Pagar, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 20,
                    ItemClicks = 543,
                    ItemStatus = 1,
                    CategoryId = 7,
                    AppUserId = 18
                },
                new Item
                {
                    Id = 19,
                    ItemName = "Home Gym Equipment Set",
                    ItemPrice = 300,
                    Condition = "Slightly Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Complete home gym equipment set including dumbbells, resistance bands, and yoga mat. Achieve your fitness goals at home.",
                    ItemLocation = "Marina Bay, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 36,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 13,
                    AppUserId = 19
                },
                new Item
                {
                    Id = 20,
                    ItemName = "Handmade Wooden Coffee Table",
                    ItemPrice = 120,
                    Condition = "Good",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Handcrafted wooden coffee table in good condition. Adds a touch of rustic charm to your living space.",
                    ItemLocation = "Jurong East, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 15,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 20
                },
                new Item
                {
                    Id = 21,
                    ItemName = "Portable Blender - USB Rechargeable",
                    ItemPrice = 30,
                    Condition = "New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Compact and portable blender, perfect for making smoothies on the go. USB rechargeable for convenience.",
                    ItemLocation = "Toa Payoh, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 23,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 10,
                    AppUserId = 21
                },
                new Item
                {
                    Id = 22,
                    ItemName = "Digital Camera - Canon EOS",
                    ItemPrice = 600,
                    Condition = "Excellent",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Canon EOS digital camera in excellent condition. Capture stunning photos and videos with this high-quality camera.",
                    ItemLocation = "Bishan, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 42,
                    ItemClicks = 1102,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 22
                },
                new Item
                {
                    Id = 23,
                    ItemName = "Electric Guitar - Fender Stratocaster",
                    ItemPrice = 800,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Fender Stratocaster electric guitar in like-new condition. Perfect for both beginners and experienced musicians.",
                    ItemLocation = "Sentosa, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 38,
                    ItemClicks = 987,
                    ItemStatus = 1,
                    CategoryId = 5,
                    AppUserId = 23
                },
                new Item
                {
                    Id = 24,
                    ItemName = "Smart Refrigerator - Samsung Family Hub",
                    ItemPrice = 1200,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Samsung Family Hub smart refrigerator with touchscreen and smart home features. In good working condition.",
                    ItemLocation = "Clementi, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 55,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 10,
                    AppUserId = 24
                },
                new Item
                {
                    Id = 25,
                    ItemName = "Collectible Comic Books Set",
                    ItemPrice = 150,
                    Condition = "Good",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Set of collectible comic books in good condition. Dive into the world of superheroes and adventure.",
                    ItemLocation = "Ang Mo Kio, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 20,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 7,
                    AppUserId = 25
                },
                new Item
                {
                    Id = 26,
                    ItemName = "Robot Vacuum Cleaner - Roomba",
                    ItemPrice = 300,
                    Condition = "Slightly Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Roomba robot vacuum cleaner in great condition. Effortlessly keep your home clean with smart technology.",
                    ItemLocation = "Woodlands, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 28,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 26
                },
                new Item
                {
                    Id = 27,
                    ItemName = "Kids' Educational Toys Bundle",
                    ItemPrice = 50,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Bundle of educational toys for kids. Foster learning and creativity in a fun and engaging way.",
                    ItemLocation = "Jurong West, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 15,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 7,
                    AppUserId = 27
                },
                new Item
                {
                    Id = 28,
                    ItemName = "Weightlifting Set",
                    ItemPrice = 200,
                    Condition = "Good",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Complete weightlifting set with barbell and weights. Ideal for strength training at home or in the gym.",
                    ItemLocation = "Yishun, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 33,
                    ItemClicks = 1102,
                    ItemStatus = 1,
                    CategoryId = 13,
                    AppUserId = 28
                },
                new Item
                {
                    Id = 29,
                    ItemName = "Portable Projector - Anker Nebula",
                    ItemPrice = 150,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Anker Nebula portable projector in like-new condition. Enjoy movies and presentations on the big screen.",
                    ItemLocation = "Toa Payoh, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 25,
                    ItemClicks = 987,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 29
                },
                new Item
                {
                    Id = 30,
                    ItemName = "Handmade Jewelry Set",
                    ItemPrice = 80,
                    Condition = "New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Elegant handmade jewelry set including necklace and earrings. Perfect for special occasions or daily wear.",
                    ItemLocation = "Marina Bay Sands, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 22,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 5,
                    AppUserId = 30
                },
                new Item
                {
                    Id = 31,
                    ItemName = "Gourmet Cooking Class Voucher",
                    ItemPrice = 60,
                    Condition = "Available",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Voucher for a gourmet cooking class. Learn culinary skills and enjoy a delightful cooking experience.",
                    ItemLocation = "Chinatown, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 18,
                    ItemClicks = 543,
                    ItemStatus = 1,
                    CategoryId = 12,
                    AppUserId = 1
                },
                new Item
                {
                    Id = 32,
                    ItemName = "DJI Mavic Air 2 Drone",
                    ItemPrice = 800,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "DJI Mavic Air 2 drone in like-new condition. Capture breathtaking aerial footage with this advanced drone.",
                    ItemLocation = "Orchard Road, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 48,
                    ItemClicks = 1201,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 2
                },
                new Item
                {
                    Id = 33,
                    ItemName = "Home Office Desk",
                    ItemPrice = 150,
                    Condition = "Good",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Sturdy home office desk in good condition. Ideal for remote work or studying from home.",
                    ItemLocation = "Bukit Timah, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 32,
                    ItemClicks = 987,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 3
                },
                new Item
                {
                    Id = 34,
                    ItemName = "Vintage Vinyl Record Collection",
                    ItemPrice = 120,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Collection of vintage vinyl records in good condition. Enjoy the classic sounds of music history.",
                    ItemLocation = "Tampines, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 25,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 13,
                    AppUserId = 4
                },
                new Item
                {
                    Id = 35,
                    ItemName = "Smart Thermostat - Nest Learning",
                    ItemPrice = 100,
                    Condition = "Slightly Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Nest Learning smart thermostat for efficient climate control. Save energy and customize your home's temperature.",
                    ItemLocation = "Katong, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 35,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 10,
                    AppUserId = 5
                },
                new Item
                {
                    Id = 36,
                    ItemName = "Kids' Bicycle - Schwinn",
                    ItemPrice = 80,
                    Condition = "Good",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Schwinn kids' bicycle in good condition. Perfect for young riders to learn and enjoy cycling.",
                    ItemLocation = "Serangoon, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 18,
                    ItemClicks = 543,
                    ItemStatus = 1,
                    CategoryId = 7,
                    AppUserId = 6
                },
                new Item
                {
                    Id = 37,
                    ItemName = "Digital Art Print - Abstract",
                    ItemPrice = 40,
                    Condition = "New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Abstract digital art print for home decor. Add a touch of modernity to your living space.",
                    ItemLocation = "Hougang, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 20,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 6,
                    AppUserId = 7
                },
                new Item
                {
                    Id = 38,
                    ItemName = "Wireless Earbuds - Sony WF-1000XM4",
                    ItemPrice = 180,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Sony WF-1000XM4 wireless earbuds in like-new condition. Experience premium audio quality on the go.",
                    ItemLocation = "Ang Mo Kio, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 30,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 8
                },
                new Item
                {
                    Id = 39,
                    ItemName = "Coffee Maker - Breville Barista Express",
                    ItemPrice = 300,
                    Condition = "Excellent",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Breville Barista Express coffee maker in excellent condition. Brew barista-quality coffee at home.",
                    ItemLocation = "Woodlands, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 40,
                    ItemClicks = 987,
                    ItemStatus = 1,
                    CategoryId = 10,
                    AppUserId = 9
                },
                new Item
                {
                    Id = 40,
                    ItemName = "Fitness Tracker - Fitbit Charge 4",
                    ItemPrice = 80,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Fitbit Charge 4 fitness tracker in good working condition. Monitor your health and stay active.",
                    ItemLocation = "Tanjong Pagar, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 25,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 13,
                    AppUserId = 10
                },
                new Item
                {
                    Id = 41,
                    ItemName = "Handmade Quilt - Vintage Style",
                    ItemPrice = 100,
                    Condition = "New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Handmade quilt with vintage-style patterns. Add warmth and style to your bedroom.",
                    ItemLocation = "Toa Payoh, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 22,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 11
                },
                new Item
                {
                    Id = 42,
                    ItemName = "Smart LED TV - Samsung 4K",
                    ItemPrice = 700,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Samsung 4K smart LED TV in like-new condition. Immerse yourself in stunning visuals and smart features.",
                    ItemLocation = "Raffles Place, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 55,
                    ItemClicks = 1201,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 12
                },
                new Item
                {
                    Id = 43,
                    ItemName = "Electric Scooter - Segway Ninebot",
                    ItemPrice = 400,
                    Condition = "Good",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Segway Ninebot electric scooter in good condition. Convenient and eco-friendly mode of transportation.",
                    ItemLocation = "Bishan, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 32,
                    ItemClicks = 987,
                    ItemStatus = 1,
                    CategoryId = 1,
                    AppUserId = 13
                },
                new Item
                {
                    Id = 44,
                    ItemName = "Modern Dining Table Set",
                    ItemPrice = 550,
                    Condition = "Excellent",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Modern dining table set with chairs in excellent condition. Upgrade your dining space with contemporary style.",
                    ItemLocation = "Bedok, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 45,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 14
                },
                new Item
                {
                    Id = 45,
                    ItemName = "Wireless Keyboard and Mouse Combo",
                    ItemPrice = 50,
                    Condition = "Slightly Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Wireless keyboard and mouse combo in great condition. Improve your productivity with cable-free peripherals.",
                    ItemLocation = "Yishun, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 28,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 15
                },
                new Item
                {
                    Id = 46,
                    ItemName = "Vintage Fountain Pen Collection",
                    ItemPrice = 90,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Collection of vintage fountain pens in good condition. Perfect for pen enthusiasts and collectors.",
                    ItemLocation = "Choa Chu Kang, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 25,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 6,
                    AppUserId = 16
                },
                new Item
                {
                    Id = 47,
                    ItemName = "Smart Doorbell - Ring Video Doorbell",
                    ItemPrice = 120,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Ring Video Doorbell in like-new condition. Enhance your home security with smart doorbell features.",
                    ItemLocation = "Pasir Ris, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 22,
                    ItemClicks = 789,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 17
                },
                new Item
                {
                    Id = 48,
                    ItemName = "Artificial Potted Plants Set",
                    ItemPrice = 30,
                    Condition = "New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Set of artificial potted plants to add greenery to your home. No maintenance required!",
                    ItemLocation = "Tanjong Pagar, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 18,
                    ItemClicks = 543,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 18
                },
                new Item
                {
                    Id = 49,
                    ItemName = "Outdoor Camping Gear Bundle",
                    ItemPrice = 200,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Bundle of outdoor camping gear including tent, sleeping bag, and camping stove. Gear up for your next adventure.",
                    ItemLocation = "Marina Bay, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 36,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 13,
                    AppUserId = 19
                },
                new Item
                {
                    Id = 50,
                    ItemName = "Wooden Bookshelf",
                    ItemPrice = 100,
                    Condition = "Good",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Sturdy wooden bookshelf in good condition. Organize your book collection with style.",
                    ItemLocation = "Jurong East, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 15,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 20
                },
                new Item
                {
                    Id = 51,
                    ItemName = "Wireless Charging Pad",
                    ItemPrice = 20,
                    Condition = "New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Wireless charging pad for convenient charging of your devices. Stay powered up with this sleek accessory.",
                    ItemLocation = "Toa Payoh, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 23,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 21
                },
                new Item
                {
                    Id = 52,
                    ItemName = "Smartwatch - Garmin Venu 2",
                    ItemPrice = 250,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Garmin Venu 2 smartwatch in like-new condition. Track your fitness and stay connected with this advanced wearable.",
                    ItemLocation = "Bishan, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 40,
                    ItemClicks = 1201,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 22
                },
                new Item
                {
                    Id = 53,
                    ItemName = "Vintage Vinyl Record Player",
                    ItemPrice = 180,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Vintage vinyl record player in good working condition. Enjoy your favorite tunes with a touch of nostalgia.",
                    ItemLocation = "Sentosa, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 28,
                    ItemClicks = 987,
                    ItemStatus = 1,
                    CategoryId = 8,
                    AppUserId = 23
                },
                new Item
                {
                    Id = 54,
                    ItemName = "Portable Bluetooth Speaker",
                    ItemPrice = 50,
                    Condition = "Good",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Portable Bluetooth speaker in good condition. Take your music wherever you go with this compact device.",
                    ItemLocation = "Clementi, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 25,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 24
                },
                new Item
                {
                    Id = 55,
                    ItemName = "Electric Mixer - KitchenAid",
                    ItemPrice = 120,
                    Condition = "Excellent",
                    ItemDate = DateTime.Now,
                    ItemDescription = "KitchenAid electric mixer in excellent condition. Make baking and cooking a breeze with this reliable appliance.",
                    ItemLocation = "Ang Mo Kio, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 32,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 10,
                    AppUserId = 25
                },
                new Item
                {
                    Id = 56,
                    ItemName = "Board Game Collection",
                    ItemPrice = 60,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Collection of popular board games in good condition. Bring friends and family together for game night fun.",
                    ItemLocation = "Woodlands, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 22,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 7,
                    AppUserId = 26
                },
                new Item
                {
                    Id = 57,
                    ItemName = "Smart Home Security Camera",
                    ItemPrice = 90,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Smart home security camera in like-new condition. Monitor your home remotely for added peace of mind.",
                    ItemLocation = "Jurong West, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 35,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 27
                },
                new Item
                {
                    Id = 58,
                    ItemName = "Vintage Typewriter - Royal",
                    ItemPrice = 100,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Vintage Royal typewriter in good working condition. Perfect for writers and collectors of retro items.",
                    ItemLocation = "Yishun, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 18,
                    ItemClicks = 543,
                    ItemStatus = 1,
                    CategoryId = 6,
                    AppUserId = 28
                },
                new Item
                {
                    Id = 59,
                    ItemName = "Indoor Plant - Fiddle Leaf Fig",
                    ItemPrice = 30,
                    Condition = "New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Fiddle Leaf Fig indoor plant for a touch of greenery in your home. Low maintenance and aesthetically pleasing.",
                    ItemLocation = "Toa Payoh, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 20,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 29
                },
                new Item
                {
                    Id = 60,
                    ItemName = "Digital Art Tablet - Wacom Intuos",
                    ItemPrice = 80,
                    Condition = "Slightly Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Wacom Intuos digital art tablet in great condition. Ideal for digital artists and graphic designers.",
                    ItemLocation = "Toa Payoh, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 30,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 8,
                    AppUserId = 30
                },
                new Item
                {
                    Id = 61,
                    ItemName = "Fitness Resistance Bands Set",
                    ItemPrice = 20,
                    Condition = "New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Set of fitness resistance bands for effective home workouts. Stay fit and healthy with these versatile exercise tools.",
                    ItemLocation = "Chinatown, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 25,
                    ItemClicks = 543,
                    ItemStatus = 1,
                    CategoryId = 13,
                    AppUserId = 1
                },
                new Item
                {
                    Id = 62,
                    ItemName = "Robot Vacuum Cleaner - iRobot Roomba",
                    ItemPrice = 300,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "iRobot Roomba robot vacuum cleaner in good working condition. Effortlessly keep your home clean with smart technology.",
                    ItemLocation = "Chinatown, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 28,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 2
                },
                new Item
                {
                    Id = 63,
                    ItemName = "Wireless Gaming Mouse - Logitech G Pro",
                    ItemPrice = 80,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Logitech G Pro wireless gaming mouse in like-new condition. Elevate your gaming experience with precision and speed.",
                    ItemLocation = "Bukit Timah, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 32,
                    ItemClicks = 987,
                    ItemStatus = 1,
                    CategoryId = 8,
                    AppUserId = 3
                },
                new Item
                {
                    Id = 64,
                    ItemName = "Portable Espresso Machine",
                    ItemPrice = 100,
                    Condition = "Excellent",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Portable espresso machine in excellent condition. Enjoy barista-quality coffee wherever you go.",
                    ItemLocation = "Bedok, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 25,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 10,
                    AppUserId = 4
                },
                new Item
                {
                    Id = 65,
                    ItemName = "Foldable Electric Scooter",
                    ItemPrice = 350,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Foldable electric scooter in like-new condition. Commute with ease and style using this convenient mode of transportation.",
                    ItemLocation = "Tampines, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 35,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 1,
                    AppUserId = 5
                },
                new Item
                {
                    Id = 66,
                    ItemName = "Bluetooth Headphones - Sony WH-1000XM4",
                    ItemPrice = 250,
                    Condition = "Excellent",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Sony WH-1000XM4 Bluetooth headphones in excellent condition. Immerse yourself in high-quality audio with noise-canceling technology.",
                    ItemLocation = "Hougang, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 42,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 6
                },
                new Item
                {
                    Id = 67,
                    ItemName = "Vintage Camera - Nikon F2",
                    ItemPrice = 180,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Nikon F2 vintage camera in good working condition. Capture timeless moments with this classic film camera.",
                    ItemLocation = "Serangoon, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 30,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 7
                },
                new Item
                {
                    Id = 68,
                    ItemName = "Smart LED Bulbs Set",
                    ItemPrice = 40,
                    Condition = "New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Set of smart LED bulbs for customizable lighting. Transform your home with modern and energy-efficient lighting.",
                    ItemLocation = "Ang Mo Kio, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 18,
                    ItemClicks = 543,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 8
                },
                new Item
                {
                    Id = 69,
                    ItemName = "Digital Piano - Yamaha P-125",
                    ItemPrice = 600,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Yamaha P-125 digital piano in like-new condition. Perfect for aspiring musicians and music enthusiasts.",
                    ItemLocation = "Woodlands, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 25,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 5,
                    AppUserId = 9
                },
                new Item
                {
                    Id = 70,
                    ItemName = "Wireless Gaming Keyboard - Razer BlackWidow",
                    ItemPrice = 120,
                    Condition = "Slightly Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Razer BlackWidow wireless gaming keyboard in great condition. Enhance your gaming setup with this high-performance keyboard.",
                    ItemLocation = "Jurong West, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 28,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 8,
                    AppUserId = 10
                },
                new Item
                {
                    Id = 71,
                    ItemName = "Professional Camera Lens - Canon EF 24-70mm",
                    ItemPrice = 800,
                    Condition = "Excellent",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Canon EF 24-70mm professional camera lens in excellent condition. Capture sharp and detailed images with this high-quality lens.",
                    ItemLocation = "Toa Payoh, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 35,
                    ItemClicks = 987,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 11
                },
                new Item
                {
                    Id = 72,
                    ItemName = "Wireless Charger Stand",
                    ItemPrice = 30,
                    Condition = "New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Wireless charger stand for convenient charging of your devices. Stay organized and powered up with this sleek accessory.",
                    ItemLocation = "Chinatown, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 22,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 12
                },
                new Item
                {
                    Id = 73,
                    ItemName = "Vintage Vinyl Record Player Stand",
                    ItemPrice = 70,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Stand for vintage vinyl record players in good condition. Showcase and organize your vinyl collection with style.",
                    ItemLocation = "Bishan, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 18,
                    ItemClicks = 543,
                    ItemStatus = 1,
                    CategoryId = 6,
                    AppUserId = 13
                },
                new Item
                {
                    Id = 74,
                    ItemName = "Portable Monitor - ASUS ZenScreen",
                    ItemPrice = 200,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "ASUS ZenScreen portable monitor in like-new condition. Boost your productivity with an additional display on the go.",
                    ItemLocation = "Bedok, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 30,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 4,
                    AppUserId = 14
                },
                new Item
                {
                    Id = 75,
                    ItemName = "Fitness Dumbbell Set",
                    ItemPrice = 80,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Set of fitness dumbbells in good condition. Build strength and stay active with these versatile workout tools.",
                    ItemLocation = "Ang Mo Kio, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 20,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 13,
                    AppUserId = 15
                },
                new Item
                {
                    Id = 76,
                    ItemName = "Gaming Console - PlayStation 5",
                    ItemPrice = 600,
                    Condition = "Excellent",
                    ItemDate = DateTime.Now,
                    ItemDescription = "PlayStation 5 gaming console in excellent condition. Immerse yourself in the latest gaming experiences with this powerful console.",
                    ItemLocation = "Clementi, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 40,
                    ItemClicks = 987,
                    ItemStatus = 1,
                    CategoryId = 8,
                    AppUserId = 16
                },
                new Item
                {
                    Id = 77,
                    ItemName = "Modern Wall Clock",
                    ItemPrice = 25,
                    Condition = "New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Modern wall clock to enhance your home decor. Stay punctual in style with this contemporary timepiece.",
                    ItemLocation = "Hougang, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 25,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 17
                },
                new Item
                {
                    Id = 78,
                    ItemName = "Wireless Soundbar - Bose 700",
                    ItemPrice = 350,
                    Condition = "Like New",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Bose 700 wireless soundbar in like-new condition. Elevate your home entertainment experience with immersive sound.",
                    ItemLocation = "Jurong West, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 35,
                    ItemClicks = 654,
                    ItemStatus = 1,
                    CategoryId = 8,
                    AppUserId = 18
                },
                new Item
                {
                    Id = 79,
                    ItemName = "Camping Tent - 4 Person",
                    ItemPrice = 120,
                    Condition = "Used",
                    ItemDate = DateTime.Now,
                    ItemDescription = "4-person camping tent in good condition. Enjoy outdoor adventures with this reliable and spacious tent.",
                    ItemLocation = "Marina Bay, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 22,
                    ItemClicks = 765,
                    ItemStatus = 1,
                    CategoryId = 13,
                    AppUserId = 19
                },
                new Item
                {
                    Id = 80,
                    ItemName = "Air Purifier - Dyson Pure Cool",
                    ItemPrice = 300,
                    Condition = "Excellent",
                    ItemDate = DateTime.Now,
                    ItemDescription = "Dyson Pure Cool air purifier in excellent condition. Breathe clean air with advanced filtration technology.",
                    ItemLocation = "Tanjong Pagar, Singapore",
                    ImageUrl = "https://via.placeholder.com/300",
                    ItemLikes = 30,
                    ItemClicks = 876,
                    ItemStatus = 1,
                    CategoryId = 9,
                    AppUserId = 20
                }
            );
        }
    }
}
