// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sellora.Server.Data;

#nullable disable

namespace Sellora.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240125111745_ff")]
    partial class ff
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.Key", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DataProtected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsX509Certificate")
                        .HasColumnType("bit");

                    b.Property<string>("Use")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Use");

                    b.ToTable("Keys", (string)null);
                });

            modelBuilder.Entity("Duende.IdentityServer.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConsumedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.HasIndex("ConsumedTime");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.HasIndex("SubjectId", "SessionId", "Type");

                    b.ToTable("PersistedGrants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "595b2485-3bfa-4b70-9209-7526bdb84f37",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        },
                        new
                        {
                            UserId = "b1675205-1948-44ec-8b55-b0cb71d1f84e",
                            RoleId = "bd2bcf0c-20db-474f-8407-5a6b159518bb"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Sellora.Server.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserLastOnline")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("UserRegDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "282d3c5a-c765-4e7a-8d56-a7d31e356754",
                            Email = "admin@localhost.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBSYLyxda4XtGYA1WZqdi26jkOtQCyyw3VwCxzN8+mMDIFAitni+bM/BzW4suhFUWQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "af17f7c6-99d3-4bf4-aadd-a007182ca846",
                            TwoFactorEnabled = false,
                            UserFirstName = "Admin",
                            UserLastName = "User",
                            UserLastOnline = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6820),
                            UserName = "admin@localhost.com",
                            UserRegDate = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6819)
                        },
                        new
                        {
                            Id = "b1675205-1948-44ec-8b55-b0cb71d1f84e",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e14f9805-1c8d-4ef2-ad25-0704ca6a2981",
                            Email = "user@localhost.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@LOCALHOST.COM",
                            NormalizedUserName = "USER",
                            PasswordHash = "AQAAAAIAAYagAAAAEBfX3BcwYoPeF1hEl8GF7SMf3r7DulWz6i3ty3pzzkw2HpCEd0up8UAdeTXdYNeZ3w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a61086c7-47de-46c6-a68d-204b66cbf230",
                            TwoFactorEnabled = false,
                            UserFirstName = "User",
                            UserLastName = "User",
                            UserLastOnline = new DateTime(2024, 1, 25, 19, 17, 45, 61, DateTimeKind.Local).AddTicks(258),
                            UserName = "user",
                            UserRegDate = new DateTime(2024, 1, 25, 19, 17, 45, 61, DateTimeKind.Local).AddTicks(235)
                        });
                });

            modelBuilder.Entity("Sellora.Shared.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserHPNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserLastOnline")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserRegDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserDescription = "Passionate about all things digital and SEO wizardry 🚀 | Helping businesses climb the search engine ranks 📈 | Coffee enthusiast ☕ | Explorer of new tech and trends 🌐 | #SEOExpert #DigitalMarketing",
                            UserEmail = "sy123@gmail.com",
                            UserFirstName = "Seo",
                            UserHPNum = "88123123",
                            UserLastName = "Yeong",
                            UserLastOnline = new DateTime(2024, 1, 25, 19, 17, 45, 139, DateTimeKind.Local).AddTicks(1869),
                            UserName = "SeoCoolSeoYeong",
                            UserPassword = "AQAAAAIAAYagAAAAENO673AtYdPO+vUnylfYhasFoJgGdSwz2e4fBeEdEz5p+Z5ymtSDNH6uy5Dm06MrJw==",
                            UserRegDate = new DateTime(2024, 1, 25, 19, 17, 45, 139, DateTimeKind.Local).AddTicks(1852)
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserDescription = "Creative soul navigating the digital realm 🌟 | Graphic designer by day, dreamer by night ✨ | Turning ideas into visual wonders 🎨 | Coffee addict ☕ | Embracing the beauty of design and storytelling 🖌️ | #GraphicDesigner #Dreamer",
                            UserEmail = "tt123@gmail.com",
                            UserFirstName = "Tina",
                            UserHPNum = "88445566",
                            UserLastName = "Tan",
                            UserLastOnline = new DateTime(2024, 1, 25, 19, 17, 45, 181, DateTimeKind.Local).AddTicks(2277),
                            UserName = "TT_4Me",
                            UserPassword = "AQAAAAIAAYagAAAAED63TyVCzpGHdLTDEtipb9fi37XlepUGclNx4m/iIwlknruz0Ml6lKQpUcX5NAhsyQ==",
                            UserRegDate = new DateTime(2024, 1, 25, 19, 17, 45, 181, DateTimeKind.Local).AddTicks(2245)
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserDescription = "Adventurous spirit with a flair for tech and innovation 🚀 | Coding maestro by day, gaming wizard by night 🎮 | Constantly exploring the digital frontier 💻 | Fuelled by curiosity and a love for challenges 🌐 | Living life one line of code at a time! #TechExplorer #GamingEnthusiast",
                            UserEmail = "kl23@gmail.com",
                            UserFirstName = "Kaynan",
                            UserHPNum = "85445666",
                            UserLastName = "Loh",
                            UserLastOnline = new DateTime(2024, 1, 25, 19, 17, 45, 224, DateTimeKind.Local).AddTicks(6191),
                            UserName = "Kay_today",
                            UserPassword = "AQAAAAIAAYagAAAAEEZK2InD9yrcNcFzfmUXzeETCq/9JArCtWiMbnj5uG7ZqsYShFHvYrD8/Whj5vuHxQ==",
                            UserRegDate = new DateTime(2024, 1, 25, 19, 17, 45, 224, DateTimeKind.Local).AddTicks(6164)
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserDescription = "Passionate about coding adventures and tech wonders 🌟 | Coffee-fueled developer by day, gaming enthusiast by night 🎮 | Embracing challenges and turning ideas into reality 💡 | #CodeExplorer #TechEnthusiast",
                            UserEmail = "alex.smith@example.com",
                            UserFirstName = "Alex",
                            UserHPNum = "9876543210",
                            UserLastName = "Smith",
                            UserLastOnline = new DateTime(2024, 1, 25, 19, 17, 45, 263, DateTimeKind.Local).AddTicks(702),
                            UserName = "AdventureCoder",
                            UserPassword = "AQAAAAIAAYagAAAAEJLBORPRf4ni8vdMG3WYjOpt2iLMkfJjSarEGPzmXg3Al2FdK91isUwPgQtptQsHaQ==",
                            UserRegDate = new DateTime(2024, 1, 25, 19, 17, 45, 263, DateTimeKind.Local).AddTicks(679)
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserDescription = "Digital nomad exploring the virtual realms 🌍 | Coding on-the-go and crafting unique digital experiences ✨ | Passionate about connecting through technology 🚀 | #DigitalNomad #CodeExplorer",
                            UserEmail = "emma.johnson@example.com",
                            UserFirstName = "Emma",
                            UserHPNum = "8765432109",
                            UserLastName = "Johnson",
                            UserLastOnline = new DateTime(2024, 1, 25, 19, 17, 45, 300, DateTimeKind.Local).AddTicks(1470),
                            UserName = "DigitalNomad21",
                            UserPassword = "AQAAAAIAAYagAAAAEMinDC7PtNRI/iQRKVkeQRbv40oeT50wNpezXJohGZs9YS8IwzGu9rmNnJWGTiujJA==",
                            UserRegDate = new DateTime(2024, 1, 25, 19, 17, 45, 300, DateTimeKind.Local).AddTicks(1457)
                        });
                });

            modelBuilder.Entity("Sellora.Shared.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Technology",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6550),
                            DateUpdated = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6550),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Fashion",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6552),
                            DateUpdated = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6553),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Sellora.Shared.Domain.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemClicks")
                        .HasColumnType("int");

                    b.Property<DateTime>("ItemDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemLikes")
                        .HasColumnType("int");

                    b.Property<string>("ItemLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemPrice")
                        .HasColumnType("int");

                    b.Property<int>("ItemStatus")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Sellora.Shared.Domain.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppUserID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportTitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SaleTransactionID")
                        .HasColumnType("int");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<int?>("SwapTransactionID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserID");

                    b.HasIndex("SaleTransactionID");

                    b.HasIndex("StaffID");

                    b.HasIndex("SwapTransactionID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Sellora.Shared.Domain.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ReviewRating")
                        .HasColumnType("int");

                    b.Property<string>("ReviewTitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SaleTransactionID")
                        .HasColumnType("int");

                    b.Property<int?>("SwapTransactionID")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserID");

                    b.HasIndex("SaleTransactionID");

                    b.HasIndex("SwapTransactionID");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Sellora.Shared.Domain.SaleTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUserId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ItemId");

                    b.ToTable("SaleTransactions");
                });

            modelBuilder.Entity("Sellora.Shared.Domain.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("StaffAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StaffDepartment")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StaffEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffFirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StaffHPNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StaffHireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StaffLastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("StaffPosition")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6094),
                            DateUpdated = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6099),
                            StaffAddress = "Temasek Polytechnic",
                            StaffDepartment = "Full Stack Development",
                            StaffEmail = "2102197G@student.tp.edu.sg",
                            StaffFirstName = "Ryan",
                            StaffHPNum = "99991111",
                            StaffHireDate = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6090),
                            StaffLastName = "Chong",
                            StaffPosition = "Lead Developer",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6104),
                            DateUpdated = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6105),
                            StaffAddress = "Temasek Polytechnic",
                            StaffDepartment = "Full Stack Development",
                            StaffEmail = "2203567i@student.tp.edu.sg",
                            StaffFirstName = "Lucas",
                            StaffHPNum = "99992222",
                            StaffHireDate = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6103),
                            StaffLastName = "Do",
                            StaffPosition = "Lead Developer",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6108),
                            DateUpdated = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6109),
                            StaffAddress = "Design Avenue",
                            StaffDepartment = "User Experience Design",
                            StaffEmail = "emily.ng@example.com",
                            StaffFirstName = "Emily",
                            StaffHPNum = "88882222",
                            StaffHireDate = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6107),
                            StaffLastName = "Ng",
                            StaffPosition = "Senior UI/UX Designer",
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6112),
                            DateUpdated = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6112),
                            StaffAddress = "Data Center Lane",
                            StaffDepartment = "Database Management",
                            StaffEmail = "daniel.liu@example.com",
                            StaffFirstName = "Daniel",
                            StaffHPNum = "77773333",
                            StaffHireDate = new DateTime(2024, 1, 25, 19, 17, 45, 22, DateTimeKind.Local).AddTicks(6111),
                            StaffLastName = "Liu",
                            StaffPosition = "Database Administrator",
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("Sellora.Shared.Domain.SwapTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppUser1Id")
                        .HasColumnType("int");

                    b.Property<int?>("AppUser2Id")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SwapItem1Id")
                        .HasColumnType("int");

                    b.Property<int?>("SwapItem2Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUser1Id");

                    b.HasIndex("AppUser2Id");

                    b.HasIndex("SwapItem1Id");

                    b.HasIndex("SwapItem2Id");

                    b.ToTable("SwapTransactions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Sellora.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Sellora.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sellora.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Sellora.Server.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sellora.Shared.Domain.Item", b =>
                {
                    b.HasOne("Sellora.Shared.Domain.AppUser", "AppUser")
                        .WithMany("Items")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sellora.Shared.Domain.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Sellora.Shared.Domain.Report", b =>
                {
                    b.HasOne("Sellora.Shared.Domain.AppUser", "AppUser")
                        .WithMany("Reports")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sellora.Shared.Domain.SaleTransaction", "SaleTransaction")
                        .WithMany()
                        .HasForeignKey("SaleTransactionID");

                    b.HasOne("Sellora.Shared.Domain.Staff", "Staff")
                        .WithMany("Reports")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sellora.Shared.Domain.SwapTransaction", "SwapTransaction")
                        .WithMany()
                        .HasForeignKey("SwapTransactionID");

                    b.Navigation("AppUser");

                    b.Navigation("SaleTransaction");

                    b.Navigation("Staff");

                    b.Navigation("SwapTransaction");
                });

            modelBuilder.Entity("Sellora.Shared.Domain.Review", b =>
                {
                    b.HasOne("Sellora.Shared.Domain.AppUser", "AppUser")
                        .WithMany("Reviews")
                        .HasForeignKey("AppUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sellora.Shared.Domain.SaleTransaction", "SaleTransaction")
                        .WithMany()
                        .HasForeignKey("SaleTransactionID");

                    b.HasOne("Sellora.Shared.Domain.SwapTransaction", "SwapTransaction")
                        .WithMany()
                        .HasForeignKey("SwapTransactionID");

                    b.Navigation("AppUser");

                    b.Navigation("SaleTransaction");

                    b.Navigation("SwapTransaction");
                });

            modelBuilder.Entity("Sellora.Shared.Domain.SaleTransaction", b =>
                {
                    b.HasOne("Sellora.Shared.Domain.AppUser", "AppUser")
                        .WithMany("SaleTransactions")
                        .HasForeignKey("AppUserId");

                    b.HasOne("Sellora.Shared.Domain.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("AppUser");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Sellora.Shared.Domain.SwapTransaction", b =>
                {
                    b.HasOne("Sellora.Shared.Domain.AppUser", "AppUser1")
                        .WithMany()
                        .HasForeignKey("AppUser1Id");

                    b.HasOne("Sellora.Shared.Domain.AppUser", "AppUser2")
                        .WithMany()
                        .HasForeignKey("AppUser2Id");

                    b.HasOne("Sellora.Shared.Domain.Item", "SwapItem1")
                        .WithMany()
                        .HasForeignKey("SwapItem1Id");

                    b.HasOne("Sellora.Shared.Domain.Item", "SwapItem2")
                        .WithMany()
                        .HasForeignKey("SwapItem2Id");

                    b.Navigation("AppUser1");

                    b.Navigation("AppUser2");

                    b.Navigation("SwapItem1");

                    b.Navigation("SwapItem2");
                });

            modelBuilder.Entity("Sellora.Shared.Domain.AppUser", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Reports");

                    b.Navigation("Reviews");

                    b.Navigation("SaleTransactions");
                });

            modelBuilder.Entity("Sellora.Shared.Domain.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Sellora.Shared.Domain.Staff", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
